[package]
name = "api-stress-tester"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full", "macros"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
hyper = "0.13"
hyper-tls = "0.4.1"